### ISSUE TITLE
Where can the real parameters of the simulation be found?

### ISSUE THREAD

**Issue by srzhang90s** [Flash-X/Workflows#2]
All the quantities are made dimensionless using properties of the fluid. The temperature is scaled using the following relationship,

`T_scaled = (T_real-T_bulk)/(T_wall-T_bulk)`

You should read some of my papers to get a better understanding of the physics:

https://www.sciencedirect.com/science/article/pii/S0021999124003711?via%3Dihub

_Originally posted by @akashdhruv in https://github.com/Flash-X/Workflows/issues/1#issuecomment-2323095731_

**Comment by srzhang90s** [comment]
Hello Akash,
I hope you are doing well.
Could you please let me know where I can find the real parameters for this tutorial case? For example, where are the values of `T_bulk` and `T_wall` given in the code? Thank you so much.

Best,
Shawn

**Comment by akashdhruv** [comment]
The fluid is FC72. Here is the paper: 

https://www.sciencedirect.com/science/article/abs/pii/S0017931021009315

**Comment by srzhang90s** [comment]
> The fluid is FC72. Here is the paper:
> 
> https://www.sciencedirect.com/science/article/abs/pii/S0017931021009315

Hello Akash,
Thank you for your reply.
Maybe I didn't describe it clearly. I'd like to know where to set the `T_bulk` and `T_wall` in the Flash-X code. Or do these quantities not need to appear in the code? Thank you so much.

**Comment by akashdhruv** [comment]
You don't supply the values for T_bulk or T_wall, those are baked into the Stefan number calculation. Please read the section 2 of the paper carefully and you should be able to figure it out.

**Comment by srzhang90s** [comment]
Hello Akash,
Thank you so much for your quick response. Yes, I understand.

**Comment by srzhang90s** [comment]
Hello Akash,
I hope you are doing well. 
I want to know how Mass transfer and Temperature source terms are implemented from a code perspective. Which part should I check specifically? Or do you recommend not looking at the current `Workflow` version but the latest `FlashX` version? So which unit is the specific code in? Thank you so much.

Best,
Shawn

**Comment by srzhang90s** [comment]
Hello, should I open another Issue to discuss this? Thank you so much.

**Comment by akashdhruv** [comment]
Hello please look at the latest version from the main branch and try to understand the structure of the code. Learn how to execute the setup script.

If you want to get deeper into the code you can start from `Driver/DriverMain/Incomp/Driver_evolveAll.F90`. The file is written so that you can follow along the algorithm. When you are familiar with the structure of the code, the setup scripts, and the Config file, you will be able to locate different subroutines that apply different numerics.

**Comment by akashdhruv** [comment]
Also please close this issue and open an issue on Flash-X main repo if you have more questions related to the code.

**Comment by akashdhruv** [comment]
> Hello please look at the latest version from the main branch and try to understand the structure of the code. Learn how to execute the setup script.
> 
> If you want to get deeper into the code you can start from `Driver/DriverMain/Incomp/Driver_evolveAll.F90`. The file is written so that you can follow along the algorithm. When you are familiar with the structure of the code, the setup scripts, and the Config file, you will be able to locate different subroutines that apply different numerics.

Referring to the main branch of Flash-X, evaporation and multiphase related forcing are under `physics/Multiphase/MultiphaseMain` and `physics/Multiphase/MultiphaseEvap`

**Comment by akashdhruv** [comment]
You can also use are generative AI tool to help you navigate the source code. See this issue:

https://github.com/Flash-X/Flash-X/issues/778

**Comment by srzhang90s** [comment]
Dear Akash,
Thank you so much for your detailed explanation. It helps me a lot. The generative AI tool is really a great idea.
